# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-30 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='picture',
        ),
    ]
